abcproject/abcapp/urls.py
from .import views
from django.urls import path
app_name='abcapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

abcproject/abcproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('abcapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

abcproject/abcapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='pictures')

    def __str__(self):
        return self.name

abcproject/abcapp/forms.py
from .models import movie
from django import forms

class Movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','image']

abcproject/abcapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import Movieform

# Create your views here.
def index(request):
    movie1 = movie.objects.all()
    context = {'movie_list': movie1}
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie1=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie1':movie1})
def add(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        image=request.FILES['image']
        movie1=movie(name=name,desc=desc,year=year,image=image)
        movie1.save()
    return render(request,'add.html')
def update(request,id):
    movie1=movie.objects.get(id=id)
    form=Movieform(request.POST or None,request.FILES,instance=movie1)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'movie1':movie1})
def delete(request,id):
    if request.method=='POST':
        movie1=movie.objects.get(id=id)
        movie1.delete()
        return redirect('/')
    return render(request,'delete.html')

abcproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align: center">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your name"><br>
    <input type="text" name="desc" placeholder="enter your description"><br>
    <input type="text" name="year" placeholder="enter your year"><br>
    <input type="file" name="image" ><br>
    <input type="submit">
</form>

</body>
</html>
{% endblock %}

abcproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    MOVIES
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

abcproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    ARE YOU SURE TO DELETE THIS MOVIE?
    <input type="submit">
</form>

abcproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie1.image.url}}" width="500" height="550" >

       </div>
        <div class="col-md-6">
            <h2>{{movie1.name}}</h2><br>
            <h4>{{movie1.desc}}</h4><br>
            <h4>{{movie1.year}}</h4><br>
            <a class="btn btn-warning"href="{% url 'abcapp:update' movie1.id %}">Update</a>
            <a class="btn btn-danger"href="{% url 'abcapp:delete' movie1.id %}">Delete</a>

        </div>
    </div>
</div>
{% endblock %}

abcproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
   {{form.as_p}}
    <input type="submit">
</form>

abcproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<!-- Image and text -->
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img  src="{{i.image.url}}" class="card-img-top" alt=" " width="100px" height="200px">
                <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                      <p class="card-text">{{i.desc}}</p>
                      <a href="{% url 'abcapp:detail' i.id %}" class="btn btn-primary">View Details</a>
                  </div>
            </div>
        </div>
            {% endfor %}
    </div>
</div>

{% endblock %}