ecommerce/Searchapp/urls.py
from django.urls import path
from .import views

app_name='Searchapp'
urlpatterns =[
    path('',views.SearchResult,name='SearchResult'),
]

ecommerce/cartapp/urls.py
from django.urls import path
from .import views

app_name='cartapp'
urlpatterns =[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('trash/<int:product_id>/', views.trash, name='trash')
]

ecommerce/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce',include('ecommerceapp.urls')),
    path('Searchapp/',include('Searchapp.urls')),
    path('cartapp/',include('cartapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce',include('ecommerceapp.urls')),
    path('Searchapp/',include('Searchapp.urls')),
    path('cartapp/',include('cartapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerceapp/urls.py
from django.urls import path
from .import views
app_name='ecommerceapp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name="prodCatdetail"),
]

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css ">
    <meta name="description" content="{% block metadescription %} {% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    </body>
    </html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    this is the cart page.proceed to review your items and place the order...!
{% endblock %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                There is no product in the cart
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'ecommerceapp:allProdCat' %}">here</a>to continue shopping
            </p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Your shopping cart</h1>
            <br>
        </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-lg-6">
            <table class="table my_table">
                <thead class="my_thead">
                <tr>
                    <th colspan="5" class="my_thead">
                        Items
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{ cart_item.product.image.url }}" alt="width=100px" height="100px" class="float-left rounded custom_image"></a>

                    </td>
                    <td class="text-left">
                        {{ cart_item.product.name }}<br>
                        SKU:{{cart_item.product.id  }}<br>
                        Price :$ {{cart_item.product.price  }}<br>
                        Qty:{{ cart_item.quantity }} x $ {{ cart_item }}
                    </td>
                    <td>
                        $ {{ cart_item.sub_total }}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-circle-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:trash' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                        {% else %}
                        <td>
                            &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cartapp:trash' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your items before proceeding with the payment..
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Total price is: <strong>{{ total }}</strong>

                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allProdCat' %}"  class="btn btn-secondary my_button">Continue shopping</a>
        </div>
    </div>
    </div>
    </div>
    {% endif %}
    {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155  }}
    {% else %}
            WELCOME TO OUR STORE YOU CAN BUY DIFFERENT PRODUCTS...!
    {%  endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-ABC STORE
    {% else %}
            SEE OUR NEW COLLECTION-ABC STORE...!
    {%  endif %}
{% endblock %}
{% block content %}
    {% if category %}
    <div>
        <div>
            <p><a href="{% url 'ecommerceapp:allProdCat' %}"> OUR PRODUCT COLLECTIONS</a></p>
        </div>
    </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
</div>
    <br>
<div>
    <h1 class="text-center my_title">{{ category.name }}</h1>
    <p class="text-justify">{{ category.descripion }}</p>
</div>
    {% else %}
    <div>
        <img class="my_image_padding" src="{% static 'img/banner1.jpg' %}" alt="our products" width="1120px" height="500px">
    </div>

    <div>
    <h1 class="text-center my_title">our product collections</h1class>
    <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
    </div>
{% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18em;">
                <div class="mx-auto">
                <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
            </div>
        <div class="card-body">
            <h4>{{ product.name }}</h4>
            <h4>{{ product.price }}</h4>
        </div>
        </div>
    </div>
    {% endfor %}
</div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}


    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
    {% endfor %}
    </div>
        {% endif %}
    </div>
<br>
</div>
{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Organic tech pvt ltd.All rights reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat' %}"> <img src="{%  static 'img/design1.jpg' %}" alt="Logoimage">
    </center>
</header>

ecommerce/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
hlooo
</body>
</html>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Market
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">AllProducts</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
              {% endfor %}
                      </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
                <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{ item_count }})</a>
        </li>
      {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'Searchapp:SearchResult' %}" method="get">
          {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{product.description|truncatewords:155  }}

{% endblock %}
{% block title %}
    {% if category %}
        {{product.name}}-ORGANIC STORE
    {%  endif %}
{% endblock %}
{% block content %}
<div class="row my_prod">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a>{{ product.name }}</p>

    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width: 18rem;">
            <img src="{{ product.image.url }}" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_product_title">{{ product.name }}</h1>
        <p>${{ product.price }}</p>
        <p class="my_title">PRODUCT DESCRIPTION</p>
        <p class="text-justify my_prod_text">{{ product.description }}</p>
        {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
        {% else %}
             <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">Add to Cart</a>
        {% endif %}
    </div>
</div>
</div>
</div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

            WE HAVE VARIETY OF PRODUCTS...!
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{ query }}"</b></p>
</div>
    <div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18em;">
                <div class="mx-auto">
                <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                </div>
                <div class="card-body">
                   <h4>{{ product.name }}</h4>
                   <h4>{{ product.price }}</h4>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}