bookproject/bookapp/urls.py
from django.urls import path
from .import views
app_name='bookapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('book/<int:book_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete')
]

bookproject/bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bookapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookproject/bookapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name=models.CharField(max_length=250)
    author=models.CharField(max_length=200)
    year=models.IntegerField()
    desc=models.TextField()
    image=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

bookproject/bookapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['name','author','year','desc','image']

bookproject/bookapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Book
from .forms import BookForm
# Create your views here.
def index(request):
    book=Book.objects.all()
    context={
        'book_list':book
    }
    return render(request,'index.html',context)
def detail(request,book_id):
    book=Book.objects.get(id=book_id)
    return render(request,'detail.html',{'book':book})
def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        author=request.POST.get('author')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        image=request.FILES['image']
        book=Book(name=name,author=author,desc=desc,year=year,image=image)
        book.save()
    return render(request,'add.html')
def update(request,id):
    book=Book.objects.get(id=id)
    form=BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'book':book,'form':form})
def delete(request,id):
    if request.method=='POST':
        book=Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request,'delete.html')

bookproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align: center">
<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter the name of book"><br>
    <input type="text" name="author" placeholder="enter the author of book"><br>
    <input type="text" name="desc" placeholder="enter the description"><br>
    <input type="text" name="year" placeholder="enter the published year"><br>
    <input type="file" name="image" ><br>
    <input type="submit">


</form>
</body>
</html>
{% endblock %}

bookproject/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      BOOK STORE
  </a>
</nav>
{%  block body %}
{%  endblock %}
</body>
</html>

bookproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    <body style="background-color: pink;text-align: center;">
    ARE YOU WANT TO DELETE THIS BOOK?
    <input type="submit">
    </body>
</form>

bookproject/templates/detail.html
{%  extends 'base.html' %}
{%  block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ book.image.url }}" width="400" height="450"><br>
        </div>
  <div class="col-md-6">
      <h2>{{ book.name }}</h2><br>
      <h3>{{ book.author }}</h3><br>
      <h4>{{ book.desc }}</h4><br>
      <h4>{{ book.year}}</h4><br>
      <a class="btn btn-warning" href="{%  url 'bookapp:update' book.id %}">Update</a>
      <a class="btn btn-danger" href="{%  url 'bookapp:delete' book.id %}">Delete</a>
  </div>

          </div>
    </div>
{%  endblock  %}

bookproject/templates/index.html
<!-- Just an image -->
{%  extends 'base.html' %}
{%  block body %}
   <div class="container">
       <div class="row">
           {%  for i in book_list %}
                  <div class="col-md-3">
           <div class="card" style="width: 18rem;">
  <img src="{{ i.image.url }}" class="class-img-top" alt=""  height="300px">
  <div class="card-body">
    <h5 class="card-title">{{ i.name }}</h5>
    <p class="card-text">{{ author }}</p>
    <a href="{% url 'bookapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
       </div>
           {%  endfor %}
   </div>
   </div>
{%  endblock %}

bookproject/templates/update.html
<form method="post" enctype="multipart/form-data">
    <body style="background-color: pink;text-align: center">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
    </body>
</form>